version: "3.9"

services:
  pgvector:
    image: "pgvector/pgvector:pg16"
    restart: unless-stopped
    environment:
      POSTGRES_USER: perazzi
      POSTGRES_PASSWORD: perazzi
      POSTGRES_DB: perazzi
    ports:
      - "5433:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
